export enum QueueJobKeys {
  LISTEN_TRANSACTIONS = "LISTEN_TRANSACTIONS",
  LISTEN_POOLS = "LISTEN_POOLS",
  LISTEN_LIQUIDITY_EVENTS = "LISTEN_LIQUIDITY_EVENTS",
  LISTEN_COLLECT_FEES = "LISTEN_COLLECT_FEES",
  LISTEN_PROTOCOL_FEES = "LISTEN_PROTOCOL_FEES",
}
